### ISSUE TITLE
Auto-update services

### ISSUE THREAD

**Issue by aksiksi** [aksiksi/compose2nix#11]
https://askubuntu.com/questions/1480975/how-to-start-and-stop-a-systemd-service-on-a-timer

**Comment by aksiksi** [comment]
Actually, it's better to rely on an existing tool such as [Watchtower](https://github.com/containrrr/watchtower). Watchtower seems to work, although it conflicts with Systemd, which will auto-restart the service on SIGTERM.

**Comment by sirchia** [comment]
FYI I’m using podman’s auto-update feature https://docs.podman.io/en/latest/markdown/podman-auto-update.1.html scheduled from systemd.

**Comment by aksiksi** [comment]
Damn, that's pretty cool! Thanks for the pointer! I've also added a note on this to the README: https://github.com/aksiksi/compose2nix#podman-auto-update-containers

**Comment by sirchia** [comment]
Nice, although the 3rd point might be misinterpreted. It's not every restart of the service managing the container that it will check for updates, that should just restart the current image version. It is true if you meant every start of the podman provided podman-auto-update.service. Which as you've added correctly may be scheduled automatically by a timer in point 4.
