### ISSUE TITLE
Systemd UpheldBy property not generated in Install section.

### ISSUE THREAD

**Issue by vamega** [aksiksi/compose2nix#19]
I just attempted to start a service generated via compose2nix. I saw the following error message when looking through the journal logs of the unit.

> Unknown key name 'UpheldBy' in section 'Unit', ignoring

The generated unit file `/etc/systemd/system/podman-immich_server.service` had the following contents:

```
[Unit]
After=network-online.target podman-immich_postgres.service podman-immich_redis.service podman-network-immich_default.service
PartOf=podman-compose-immich-root.target
Requires=podman-immich_postgres.service podman-immich_redis.service podman-network-immich_default.service
RequiresMountsFor=/data/fast_storage/immich/library
RequiresMountsFor=/etc/localtime
UpheldBy=podman-immich_postgres.service
UpheldBy=podman-immich_redis.service
Wants=network-online.target
```

The relevant section of the nix file responsible for that unit is:

```
systemd.services."podman-immich_server" = {
  # Other parts of generated config
  unitConfig.UpheldBy = [
    "podman-immich_postgres.service"
    "podman-immich_redis.service"
  ];
  # Other parts of generated config};
};
```

I believe this should instead look like

```
systemd.services."podman-immich_server" = {
  # Other parts of generated config
  upheldBy = [
    "podman-immich_postgres.service"
    "podman-immich_redis.service"
  ];
  # Other parts of generated config};
};
```

That's the option I see [documented](https://mynixos.com/nixpkgs/option/systemd.user.units.%3Cname%3E.upheldBy)
Making this change resulted in the error disappearing.

**Comment by aksiksi** [comment]
Thanks for reporting - I have seen this before locally as well. This is indeed a bug: `UpheldBy` cannot be used in the `[Unit]` section, as noted under the table here: https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#Mapping%20of%20unit%20properties%20to%20their%20inverses

However, `upheldBy` is only available on `nixos-unstable` ([not found on 23.11](https://search.nixos.org/options?channel=23.11&from=0&size=50&sort=relevance&type=packages&query=upheldBy)), so we can't switch over to using it by default. What we can do is control this with a CLI flag (default: no `upheldBy` support).

NOTE: Under the hood, `upheldBy` maps into a writing files to `.upholds`: https://github.com/NixOS/nixpkgs/blob/d5c611fcf504321442bd91b19b3dea7e20f468e7/nixos/lib/systemd-lib.nix#L313-L317. I am not sure why it is done this way, versus just setting the unit option. Perhaps the way NixOS adds units somehow sidesteps the install (i.e., `systemctl enable`)?

**Comment by vamega** [comment]
Thanks for the quick fix. I do use unstable, so I hadn't realized it wasn't present in 23.11.
As for why nixos does that translation, I do not know. If I find out and remember this post, I'll put an update here.

**Comment by aksiksi** [comment]
My goal is to always support the 1-2 latest stable release. So after 24.05 is out, I may just cleanup the flag. Users on older releases can always pin to an older commit.
