### ISSUE TITLE
Stopping many Podman units takes quite some time

### ISSUE THREAD

**Issue by aksiksi** [aksiksi/compose2nix#2]
Seems like we can hit a timeout instead of actually stopping the containers. 

Similar:

* https://discourse.nixos.org/t/oci-container-systemd-service-not-able-to-stop/31614

**Comment by aksiksi** [comment]
I think that this is specific to some containers that somehow do not correctly handle SIGTERM. Could be Podman specific too.

**Comment by sirchia** [comment]
I also experienced this and found it to be cause by this issue, which has been resolved in the nixpkgs master branch (unstable).

https://github.com/NixOS/nixpkgs/pull/248315
