### ISSUE TITLE
Quoting of health-cmd leads to health check failures in generated code

### ISSUE THREAD

**Issue by dnaq** [aksiksi/compose2nix#22]
As seen in the referenced line of the source code, the health-cmd generated when using compose2nix is quoted using single quotes, see
https://github.com/aksiksi/compose2nix/blob/3cc5f141667c1dd434570ab6cb2dbac5739edc52/compose.go#L519.

This will lead to output looking like this in the oci-container definitions:
`--health-cmd='wget -O /dev/null -q http://localhost:7474 || exit 1'`, which will try to execute an invalid command in the container
as a health check, thus causing the health check to always fail.

The fix should be simple, just removing the quotes around `'%s'`.

**Comment by aksiksi** [comment]
Thanks for reporting. Can you explain what the problem is with the example command above? Quoting the command is necessary to group together the parts of the command split by spaces.

**Comment by dnaq** [comment]
The problem is that the quoting causes docker/podman to try to execute the entirety of the line as the executable name, which causes the command to fail since there is no executable named `wget -O /dev/null -q http://localhost:7474 || exit 1` on the system.

**Comment by aksiksi** [comment]
Hmm that’s not what the Podman docs say: https://docs.podman.io/en/latest/markdown/podman-run.1.html#health-cmd-command-command-arg1

Can you share the error you are seeing in the systemd logs?

**Comment by dnaq** [comment]
On mobile right now, but if you try a simple docker compose file with a health check command similar to the one above, like `echo foo && true` you’ll see in the podman logs that it will fail to find the binary `echo foo && true`, causing the health check command to always fail and the container to be marked as unhealthy.
