### ISSUE TITLE
serviceConfig Restart no with quoted strings

### ISSUE THREAD

**Issue by timhae** [aksiksi/compose2nix#27]
Hey, thanks for the great tool! With the following minimal `docker-compose.yml`
```
services:
  test:
    image: nginx:latest
```
and `compose2nix -project test` I get
```
  systemd.services."podman-test-test" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "\"no\"";
    };
  };
```
where nix complains about the [escaped quotes](https://github.com/NixOS/nixpkgs/blob/master/nixos/lib/systemd-unit-options.nix#L35) with something like this
```
       error: A definition for option `systemd.services.podman-test-test.serviceConfig' is not of type `attribute set of (systemd option)'. Definition values:
       - In `/nix/store/yv0aqwqsvns7rx164q6lvjgy1fpvfk0c-source/test.nix':
           {
             Restart = {
               _type = "override";
               content = "\"no\"";
               priority = 500;
           ...
```
please let me know if you would like to have a PR for that

**Comment by aksiksi** [comment]
Thanks for reporting! Oof, not sure how I missed this lol... Will fix.

**Comment by timhae** [comment]
you have `// Need to use string literal here to avoid parsing as a boolean.` in your [code](https://github.com/aksiksi/compose2nix/blob/main/systemd.go#L110) so maybe it is not trivial

**Comment by timhae** [comment]
maybe the [service config type](https://github.com/aksiksi/compose2nix/blob/main/systemd.go#L58) needs to be strictly typed so the "no" does not get interpreted as boolean when the object is written to disk
