### ISSUE TITLE
Environment file contains strings with a period

### ISSUE THREAD

**Issue by ManoftheSea** [aksiksi/compose2nix#30]
I'm trying to make use of compose2nix, thank you.  The cisagov/Malcolm project has env_files that contain strings like "bootstrap.memory_lock=true".  The key "virtualisation.oci-containers.containers.*.environment" sees these as "not of type string".

I believe they just need to be wrapped in quotations within the .nix file.

**Comment by aksiksi** [comment]
Thanks for reporting! Will fix this shortly.

**Comment by aksiksi** [comment]
v0.2.1 contains the fix: https://github.com/aksiksi/compose2nix/releases/tag/v0.2.1
