### ISSUE TITLE
Support env_file as top-level service element

### ISSUE THREAD

**Issue by ElliottSullingeFarrall** [aksiksi/compose2nix#45]
I have been using the `env_files` flag to include environment files in my services but I don't like that this includes the files for every service.

Would it be possible to add support for using the `env_files` element directly so environment files can then be specified per service?

**Comment by aksiksi** [comment]
This should already be supported. I'll update the README and add a test shortly.

**Comment by aksiksi** [comment]
Actually, there is a fix needed to cases where both `-env_files=...` is passed in and `env_file` is set on the Compose service. Working on it now.

**Comment by ElliottSullingeFarrall** [comment]
Just tried out the update and it works but I was thinking more of being able to have environment files included in the corresponding `environmentFiles` for the oci-container. The path for this environment file wouldn't necessarily have to exist when compose2nix runs (similar to `volumes` and `devices`).

For my use case, I have environment files created using `environment.etc` that I want my containers to read but these environment files can be modified through other means so I can't just have compose2nix read the contents of them pre-build. At the moment, my only option is to use the `env_files` flag but this results in containers sharing all the environment files with each other.

Not sure if this would require a whole new feature.

**Comment by aksiksi** [comment]
There is an existing flag `-env_files_only` that allows you to *only* include env files in the NixOS `environmentFiles` setting.  I've just pushed a fix, so now service-level `env_files` are included the list of env files.

However, this will apply to all services. If you also want per-service control (e.g., only include env files for this service), then we could define a new Compose label - something like `compose2nix.settings.envFilesOnly=true` - to allow control of this behavior at the service level.

**Comment by ElliottSullingeFarrall** [comment]
The new fix with the `env_files_only` flag works well for my use case. It does mean moving any environment variables that are set in the compose file in with the ones I have to set through an environment file but that's not a big issue.

 However, I do think that compose2nix should not require the paths in the compose `env_file` to exist (as is the case with `volumes`, `devices`, etc). Maybe it could follow the behaviour as set by the `ignore_missing_env_files` flag?

**Comment by aksiksi** [comment]
That behavior is enforced by Docker Compose, not compose2nix.

You can use `required: false` to ignore missing env files in the `env_file` list. See: https://docs.docker.com/reference/compose-file/services/#env_file

**Comment by ElliottSullingeFarrall** [comment]
Ah of course, I forgot about the `required` option. That works very well.

Interestingly, I've noticed that setting something like
```
env_file:
      - path: /etc/test/vars.env
        required: false
```
results in
```
environmentFiles = [
      ""
      "/etc/test/vars.env"
];
```
I'm not sure where the blank entry comes from. It is generated for every service.

I've also noticed that `-include_env_files=true` is still required when using `env_file` in the compose file rather than in the command flags. This suprised me at first but does make sense.

**Comment by aksiksi** [comment]
Strange... I don't see that behavior in the [test](https://github.com/aksiksi/compose2nix/blob/main/testdata/TestEnvFilesOnly.docker.nix). Can you share one of the Compose services where you see this?

Re `include_env_files`: the tricky part is when you specify `include_env_files=true` and `env_files_only=false`, you'll have duplication of env variables since they'll be included twice - once in the `environment` map and once as a file passed to `environmentFiles`.

**Comment by ElliottSullingeFarrall** [comment]
A minimal example I tried looks like
```
# docker-compose.yml
name: test

services:
  test:
    image: test
    env_file:
      - path: test.env
        required: false
```
I then run
```
nix run github:aksiksi/compose2nix?rev=88c1dd962e2ef27e03e92ea53c5f287192991ce3 -- -include_env_files=true
```
and get 
```
# docker-compose.nix
...
virtualisation.oci-containers.containers."test-test" = {
    image = "test";
    environmentFiles = [
      ""
      "/home/elliott/Repositories/NixOS/test.env"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=test"
      "--network=test_default"
    ];
};
...
```
This causes a failure in the build process as the empty string is not of type `path`.

Yes that is the duplication I was referring to. It can be avoided by using only one of `environment` or `env_file` in the compose file (being able to use both is nice but not really needed) or making sure that the files in `env_file` don't exist when compose2nix is run and setting `required: false`. In the latter case, the variables form the environment file never get read into `environment` as the file doesn't exist. Making sure the files don't exist may be impractical in some scenarios but is useful when you are writing a config for a system different to the one on which compose2nix runs.

**Comment by aksiksi** [comment]
Thanks for sharing an example. I have fixed the empty entry bug - it was only present when running the CLI, which is why I did not see it in tests...

> It can be avoided by using only one of environment or env_file in the compose file (being able to use both is nice but not really needed) 

Using both is quite useful imo. For example, you may have some `environment` values that are overridden by an `env_file` or a compose2nix `--env_file`.

There may be something we can do here as a "default", but I think the currently available options in compose2nix + Docker Compose should cover all scenarios.

**Comment by ElliottSullingeFarrall** [comment]
Can confirm that the empty strings no longer appear and the build succeeds.

I think that the current setup works well and covers a wide range of use cases. Thanks for all your hard work on this project, its made my migration to NixOS as my docker host so much easier.
