### ISSUE TITLE
Priority of serviceConfig

### ISSUE THREAD

**Issue by ElliottSullingeFarrall** [aksiksi/compose2nix#46]
I have noticed that all `serviceConfig` attributes in the generated .nix file have a specified priority of `500` (even when created by setting something like `restart: no` or `compose2nix.systemd.service.Restart: no`). I have found that this often leads to these settings not taking precedence over default settings, making it impossible to override default systemd service settings without doing something like
```
systemd.services."podman-project-service" = {
    serviceConfig = {
      Restart = lib.mkForce "no";

    };
  };
```
Maybe there is a reason for the usage of this specific priority but it seems like omitting it would make it easier to customise the services generated by compose2nix.

**Comment by aksiksi** [comment]
I discovered during my use that the NixOS module already sets some of these systemd values internally, so using the default (low) priority of 1000 conflicts with those settings.

NixOS module sets `Restart` here: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/virtualisation/oci-containers.nix#L376

Commit where I added the priority of 500: https://github.com/aksiksi/compose2nix/commit/0dfca11252fe77abcdb24054cd61a69f9798ae87

**Comment by ElliottSullingeFarrall** [comment]
This makes sense but I'm not sure if being > 1000 is sufficient. From my observations, the priority of 500 is resulting in the systemd settings generated by compose2nix never making it into the build as they are beaten by the ones set by oci-containers.

I think the priority needs to be > 100 (see [here](https://github.com/NixOS/nixpkgs/blob/a7bf8161fa834a602278c15fcbdd955656b3aed8/lib/modules.nix#L535-L536)) but I'm not sure.

**Comment by aksiksi** [comment]
Oh interesting - nice catch! Let me see if I can write an integration test for this to confirm. If that’s the case, we can bump the compose2nix priority.

**Comment by aksiksi** [comment]
Yep, you are right... the `oci-container` module ends up silently overriding the value set by compose2nix.

I think I initially hit this problem when trying to set the `Restart` value with no priority - which obviously conflicted with the module's setting. But I never thought to confirm that the fix above worked in an integration test 🙃 

I'm working on a fix to that will set the override priority to 90. And I'll add an integration test to ensure that this value overrides the default set by NixOS.

**Comment by ElliottSullingeFarrall** [comment]
This seems to work as expected now. Tried with `restart: no` and can confirm that the resulting systemd service has `Restart=no`.
