### ISSUE TITLE
Fix Compose restart: always

### ISSUE THREAD

**Issue by aksiksi** [aksiksi/compose2nix#5]
Welp, apparently the default systemd behavior is to give up after some time. We should use the approach in the article below to align with Compose behavior.

https://michael.stapelberg.ch/posts/2024-01-17-systemd-indefinite-service-restarts/

**Comment by sirchia** [comment]
When implementing this feature consider that docker by default has an incrementing back-off delay as described here:

https://stackoverflow.com/questions/50031234/what-is-the-limiting-factor-when-docker-restart-slows-down-with-a-large-number-o/50034376#50034376

While I’m not sure it’s behaviour (start at 100ms, and keep doubling) is exactly reproducible, you might get a satisfactory result with some combination of RestartSec, RestartSteps and RestartMaxDelaySec. See https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#

Also note that a docker-compose has other restart policies like on-failure, which also allows for specification of max retries. These would of course require corresponding settings for Restart, StartLimitIntervalSec and StartLimitBurst.
