### ISSUE TITLE
Support the 'user' option

### ISSUE THREAD

**Issue by frutti93** [aksiksi/compose2nix#57]
Hi, first of all, thanks for the awesome tool. I really want to use it, but I noticed that the 'user' statement is not listed as a supported feature for services. I would be really grateful if you could look into supporting it.

**Comment by aksiksi** [comment]
It should be supported. I will update the README. Please give it a try and let me know :)

https://github.com/aksiksi/compose2nix/blob/659e84dfa077ded73d050e7c1ff68159a12c46dd/testdata/TestBasic.docker.nix#L138

**Comment by frutti93** [comment]
Just tried it, it's working.
