### ISSUE TITLE
sops-nix support?

### ISSUE THREAD

**Issue by FBIGlowie** [aksiksi/compose2nix#66]
Is support for sops-nix for secret management planned for the future?
If not, would you accept contributions that would implement this?

The thing is, my setup has sops-nix setup and I would like to keep using it for my docker containers.

Thanks!

**Comment by aksiksi** [comment]
I have never used sops-nix tbh. How would such support look like?

I am definitely open to contributions.

**Comment by FBIGlowie** [comment]
Sops-nix is another secret management method, so I guess support would be like how agenix is supported right now.
It would take the env file and add the secrets to the nix file the same way agenix does it.

I ask about contributions because I am interested in adding this feature to this project.

**Comment by aksiksi** [comment]
Sure, please go for it!

Would there be any custom logic needed, or is it just documentation?

**Comment by FBIGlowie** [comment]
Maybe a little bit of modification to the go code, but I'll see what I can do!
