### ISSUE TITLE
Is it possible to exec into containers generated by compose2nix?

### ISSUE THREAD

**Issue by hudsonpeden** [aksiksi/compose2nix#70]
I am struggling to find any information on essentially doing this:

`docker exec -it <container> /bin/bash`

With containers generated by compose2nix, Is this possible?

Appreciate this project!

**Comment by aksiksi** [comment]
Yes, you absolutely can! You’ll first need to find the container name. The easiest way to do this is via “docker ps”. And then just run the command you used but as root (so prefixed with “sudo”).

**Comment by aksiksi** [comment]
Assuming this worked. Please start a discussion thread if you have any other questions.
