### ISSUE TITLE
Question about agenix encrypted env files

### ISSUE THREAD

**Issue by bcotton** [aksiksi/compose2nix#8]
Hello! 

I'm trying to follow your instructions for adding age encrypted env files.

I've created a file with in the format of a .env file and encrypted it with agenix in my flake dir.

Then I run `compose2nix -output default.nix --env_files=/run/agenix/tailscale-keys.env --include_env_files=true`
and I get this error: ` failed to open file /run/agenix/tailscale-keys.env: open /run/agenix/tailscale-keys.env: no such file or directory`. Referencing the path to the encrypted file make no sense either.

I'm guessing that nix needs to have a reference to that age file for it to be in the store and mounted under `/run/agenix`, however , I'm running `compose2nix` on another machine from the one running the container, and that "build machine" has no config to reference and mount the secret. Chicken-and-egg methinks.

I'm guessing that you could blindly reference the path to /run/agenix env file in the resulting .nix file, but not sure.

Ideas on how to proceed?

**Comment by aksiksi** [comment]
Does the env file exist on the build machine? You can confirm by running `sudo ls -l /run/agenix`.

If the file doesn’t exist on the build machine, there is no way to avoid this. Even if we added a flag to not read the env file to compose2nix, I believe the Nix build itself would fail because the path does not exist during the container build.

**Comment by bcotton** [comment]
compose2nix fails on the build host unless you have the age file "activated" and you are building as root, which is not ideal.

When I modified the generated .nix file by hand and add:

```
    environmentFiles = [
      "/run/agenix/tailscale-keys.env"
    ];
```

Everything works fine. I'm using nixinate to start the build. So not really a "build host" per-say. Haven't gone there yet :-) 

So perhaps a flag in compose2nix to include a reference to an EnvFile, but not to try to resolve it?
